{
    "apps": [
        {
            "build_date": "2021-01-14_13:56:21", 
            "changelog": "", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "40c0539d60a6992546aab5ccb546e33b", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.2"
        }, 
        {
            "build_date": "2021-01-14_13:56:21", 
            "changelog": "", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "0ca8df5de67855682fd286bda5465dd7", 
            "name": "aliddns", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.1"
        }, 
        {
            "build_date": "2021-01-14_13:56:21", 
            "changelog": "", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "7c24c51349dccc6cd6d0b1e0caf04907", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "aria2", 
            "version": "2.2"
        }, 
        {
            "build_date": "2021-01-14_13:56:20", 
            "changelog": "", 
            "description": "CloudFlare DDNS", 
            "home_url": "Module_cfddns.asp", 
            "md5": "ca4edd444f1bdb5ed13fb2a7b7c2aa2f", 
            "name": "cfddns", 
            "tar_url": "cfddns/cfddns.tar.gz", 
            "title": "CloudFlare DDNS", 
            "version": "1.0"
        }, 
        {
            "build_date": "2021-01-14_13:56:22", 
            "changelog": "", 
            "description": "ddnspod", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "3b4acbf798d09b91162ec512ed2a7bb4", 
            "name": "ddnspod", 
            "tar_url": "ddnspod/ddnspod.tar.gz", 
            "title": "ddnspod", 
            "version": "1.5"
        }, 
        {
            "build_date": "2021-01-14_13:56:22", 
            "changelog": "", 
            "description": "ddnsto内网穿透", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "4c2216c1b1a4aaa6bbf3a504485dc4cd", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "ddnsto", 
            "version": "2.0"
        }, 
        {
            "build_date": "2021-01-14_13:56:20", 
            "changelog": "", 
            "description": "易有云 （EasyExplorer） 跨平台文件同步，支持双向同步！", 
            "home_url": "Module_easyexplorer.asp", 
            "md5": "d0f95d27685d8dacc02f2b1c4722cd72", 
            "name": "easyexplorer", 
            "tar_url": "easyexplorer/easyexplorer.tar.gz", 
            "title": "易有云", 
            "version": "2.4.1"
        }, 
        {
            "build_date": "2021-01-14_13:56:21", 
            "changelog": "", 
            "description": "迅雷快鸟，上网必备神器", 
            "home_url": "Module_fastd1ck.asp", 
            "md5": "e47cb983e8f6f04f2dcb761bb0124fa3", 
            "name": "fastd1ck", 
            "tar_url": "fastd1ck/fastd1ck.tar.gz", 
            "title": "迅雷快鸟", 
            "version": "1.6"
        }, 
        {
            "build_date": "2021-01-14_13:56:20", 
            "changelog": "", 
            "description": "支持多种协议的内网穿透软件", 
            "home_url": "Module_frpc.asp", 
            "md5": "0e435af711b33b427cc593ec17244043", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc内网穿透", 
            "version": "1.6"
        }, 
        {
            "build_date": "2021-01-14_13:56:21", 
            "changelog": "", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "a078760041cf7482480410aa386188ec", 
            "name": "frps", 
            "tar_url": "frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "1.5.2"
        }, 
        {
            "build_date": "2021-01-14_13:56:20", 
            "changelog": "", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "ea6c5eaaead2dfe48d83fbfa88a1c172", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "1.5"
        }, 
        {
            "build_date": "2021-01-14_13:56:21", 
            "changelog": "", 
            "description": "KP: Kids Protect，互联网内容过滤，保护未成年人上网~", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "7a7e0a166c064754da05932563c29505", 
            "name": "koolproxy", 
            "tar_url": "koolproxy/koolproxy.tar.gz", 
            "title": "KidsProtect", 
            "version": "3.8.4.1"
        }, 
        {
            "build_date": "2021-01-14_13:56:21", 
            "changelog": "", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "d5cbdafe0e30aab17dfc7925366ca537", 
            "name": "mdial", 
            "tar_url": "mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.3"
        }, 
        {
            "build_date": "2021-01-14_13:56:21", 
            "changelog": "", 
            "description": "通过pushplus将路由器状态推送到微信上", 
            "home_url": "Module_pushplus.asp", 
            "md5": "40bf7d05b7b6289d2bc286a2d598b8db", 
            "name": "pushplus", 
            "tar_url": "pushplus/pushplus.tar.gz", 
            "title": "pushplus全能推送", 
            "version": "0.3"
        }, 
        {
            "build_date": "2021-01-14_13:56:21", 
            "changelog": "", 
            "description": "自动签到", 
            "home_url": "Module_qiandao.asp", 
            "md5": "181b642512f6dd1eef0bc29f64d4f645", 
            "name": "qiandao", 
            "tar_url": "qiandao/qiandao.tar.gz", 
            "title": "自动签到", 
            "version": "1.5"
        }, 
        {
            "build_date": "2021-01-14_13:56:22", 
            "changelog": "", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "b40fad4578d73383d0c8473e2eb0c59e", 
            "name": "reboothelper", 
            "tar_url": "reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.6"
        }, 
        {
            "build_date": "2021-01-14_13:56:21", 
            "changelog": "", 
            "description": "一些小功能的插件", 
            "home_url": "Module_rog.asp", 
            "md5": "7c9ecf6297e6f8a16f38b05af2fa61d3", 
            "name": "rog", 
            "tar_url": "rog/rog.tar.gz", 
            "title": "ROG工具箱", 
            "version": "4.0"
        }, 
        {
            "build_date": "2021-01-14_13:56:21", 
            "changelog": "", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_routerhook.asp", 
            "md5": "eabe68c13ada2b696d323e10d2069199", 
            "name": "routerhook", 
            "tar_url": "routerhook/routerhook.tar.gz", 
            "title": "RouterHook事件回调", 
            "version": "1.2"
        }, 
        {
            "build_date": "2021-01-14_13:56:20", 
            "changelog": "", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "d4165128581262d01ea7c8495e1d05f2", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "serverChan微信推送", 
            "version": "1.4"
        }, 
        {
            "build_date": "2021-01-14_13:56:20", 
            "changelog": "", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "c7725d49c179a91e43bb26b848aa26be", 
            "name": "shellinabox", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "1.5"
        }, 
        {
            "build_date": "2021-01-14_13:56:20", 
            "changelog": "", 
            "description": "上海电信IPTV，4K IPTV 一键开启", 
            "home_url": "Module_shiptv.asp", 
            "md5": "b46af8035c7d4e5c1cc3f99f3532817a", 
            "name": "shiptv", 
            "tar_url": "shiptv/shiptv.tar.gz", 
            "title": "上海电信IPTV", 
            "version": "1.1"
        }, 
        {
            "build_date": "2021-01-14_13:56:20", 
            "changelog": "", 
            "description": "VPN全家桶, ver 4.29 build 9680", 
            "home_url": "Module_softether.asp", 
            "md5": "f64b44a7c235cd31fdf95cebfa834be9", 
            "name": "softether", 
            "tar_url": "softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "1.9"
        }, 
        {
            "build_date": "2021-01-14_13:56:22", 
            "changelog": "", 
            "description": "让路由器运行更稳定~", 
            "home_url": "Module_swap.asp", 
            "md5": "ad9d07ee809ad9777e061175d57df69d", 
            "name": "swap", 
            "tar_url": "swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.1"
        }, 
        {
            "build_date": "2021-01-14_13:56:21", 
            "changelog": "", 
            "description": "轻松用U盘挂载jffs", 
            "home_url": "Module_usb2jffs.asp", 
            "md5": "a7d86d2098b332b35a841a7dc4dc54a8", 
            "name": "usb2jffs", 
            "tar_url": "usb2jffs/usb2jffs.tar.gz", 
            "title": "USB2JFFS", 
            "version": "1.6"
        }, 
        {
            "build_date": "2021-01-14_13:56:21", 
            "changelog": "", 
            "description": "wifi boost: 路由器WiFi功率增强，增加信号覆盖范围。", 
            "home_url": "Module_wifiboost.asp", 
            "md5": "0de0e87e4aa7bc3d95672a036454aacc", 
            "name": "wifiboost", 
            "port": "8083", 
            "server": "42.192.18.234", 
            "tar_url": "wifiboost/wifiboost.tar.gz", 
            "title": "wifi boost", 
            "version": "3.5"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/koolshare/koolshare.github.io/master", 
    "md5": "761540550a84d471661597de72882860", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "1.6.6"
}