{
    "apps": [
        {
            "build_date": "2020-12-07_17:29:29", 
            "changelog": "", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "fbe472280421bad8c83c33f72cf73510", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.2"
        }, 
        {
            "build_date": "2020-12-07_17:29:29", 
            "changelog": "", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "38bf333b4cb5c01324f8d71b41a84fd5", 
            "name": "aliddns", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.1"
        }, 
        {
            "build_date": "2020-12-07_17:29:29", 
            "changelog": "", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "943ade64f7b057be4a23fc6c5cb4caa5", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "aria2", 
            "version": "2.2"
        }, 
        {
            "build_date": "2020-12-07_17:29:28", 
            "changelog": "", 
            "description": "CloudFlare DDNS", 
            "home_url": "Module_cfddns.asp", 
            "md5": "6c241b3efffac51be92f62c8ff9fba39", 
            "name": "cfddns", 
            "tar_url": "cfddns/cfddns.tar.gz", 
            "title": "CloudFlare DDNS", 
            "version": "1.0"
        }, 
        {
            "build_date": "2020-12-07_17:29:29", 
            "changelog": "", 
            "description": "ddnspod", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "c87f4d527c21bd13c5529822cb97bacd", 
            "name": "ddnspod", 
            "tar_url": "ddnspod/ddnspod.tar.gz", 
            "title": "ddnspod", 
            "version": "1.5"
        }, 
        {
            "build_date": "2020-12-07_17:29:29", 
            "changelog": "", 
            "description": "ddnsto内网穿透", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "582277ce8629a714cbf54cbdeddc2393", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "ddnsto", 
            "version": "2.0"
        }, 
        {
            "build_date": "2020-12-07_17:29:28", 
            "changelog": "", 
            "description": "易有云 （EasyExplorer） 跨平台文件同步，支持双向同步！", 
            "home_url": "Module_easyexplorer.asp", 
            "md5": "a55b8e4c2505a29a4e4647e4b274e8c8", 
            "name": "easyexplorer", 
            "tar_url": "easyexplorer/easyexplorer.tar.gz", 
            "title": "易有云", 
            "version": "2.4.1"
        }, 
        {
            "build_date": "2020-12-07_17:29:28", 
            "changelog": "", 
            "description": "迅雷快鸟，上网必备神器", 
            "home_url": "Module_fastd1ck.asp", 
            "md5": "b81e763a40487a1bfe37b18a190910ba", 
            "name": "fastd1ck", 
            "tar_url": "fastd1ck/fastd1ck.tar.gz", 
            "title": "迅雷快鸟", 
            "version": "1.6"
        }, 
        {
            "build_date": "2020-12-07_17:29:28", 
            "changelog": "", 
            "description": "支持多种协议的内网穿透软件", 
            "home_url": "Module_frpc.asp", 
            "md5": "0f77de36a516e9ad58424ed8dab05e9a", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc内网穿透", 
            "version": "1.6"
        }, 
        {
            "build_date": "2020-12-07_17:29:28", 
            "changelog": "", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "b76925656ceeb76fefeb570b829ed052", 
            "name": "frps", 
            "tar_url": "frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "1.5.2"
        }, 
        {
            "build_date": "2020-12-07_17:29:28", 
            "changelog": "", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "f9bef39c39e8438fe7ecdb244434b27e", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "1.5"
        }, 
        {
            "build_date": "2020-12-07_17:29:29", 
            "changelog": "", 
            "description": "KP: Kids Protect，互联网内容过滤，保护未成年人上网~", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "43a5ee7a92a402caf8cd46ac33f41952", 
            "name": "koolproxy", 
            "tar_url": "koolproxy/koolproxy.tar.gz", 
            "title": "KidsProtect", 
            "version": "3.8.4.1"
        }, 
        {
            "build_date": "2020-12-07_17:29:29", 
            "changelog": "", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "77ee772451a21143151fa0f0ff2689ee", 
            "name": "mdial", 
            "tar_url": "mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.3"
        }, 
        {
            "build_date": "2020-12-07_17:29:28", 
            "changelog": "", 
            "description": "通过pushplus将路由器状态推送到微信上", 
            "home_url": "Module_pushplus.asp", 
            "md5": "333ddcc0d7404911951f8b23d3fc0c46", 
            "name": "pushplus", 
            "tar_url": "pushplus/pushplus.tar.gz", 
            "title": "pushplus全能推送", 
            "version": "0.3"
        }, 
        {
            "build_date": "2020-12-07_17:29:28", 
            "changelog": "", 
            "description": "自动签到", 
            "home_url": "Module_qiandao.asp", 
            "md5": "2bf55955d34efb874fc63ceaf94307ab", 
            "name": "qiandao", 
            "tar_url": "qiandao/qiandao.tar.gz", 
            "title": "自动签到", 
            "version": "1.5"
        }, 
        {
            "build_date": "2020-12-07_17:29:29", 
            "changelog": "", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "69bcb61b8d18d9ef7fd3e8c75a1c4c9f", 
            "name": "reboothelper", 
            "tar_url": "reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.6"
        }, 
        {
            "build_date": "2020-12-07_17:29:29", 
            "changelog": "", 
            "description": "一些小功能的插件", 
            "home_url": "Module_rog.asp", 
            "md5": "ab5a0870bcb6c1fbdb2a0556b8b8060d", 
            "name": "rog", 
            "tar_url": "rog/rog.tar.gz", 
            "title": "ROG工具箱", 
            "version": "3.8"
        }, 
        {
            "build_date": "2020-12-07_17:29:28", 
            "changelog": "", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_routerhook.asp", 
            "md5": "e9fcbe63ff985372a14c164af35f28af", 
            "name": "routerhook", 
            "tar_url": "routerhook/routerhook.tar.gz", 
            "title": "RouterHook事件回调", 
            "version": "1.2"
        }, 
        {
            "build_date": "2020-12-07_17:29:28", 
            "changelog": "", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "f44cd7e9a4aa66169350d4cfbb48b032", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "serverChan微信推送", 
            "version": "1.4"
        }, 
        {
            "build_date": "2020-12-07_17:29:28", 
            "changelog": "", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "ce175bc355e05338042465623fdbe43a", 
            "name": "shellinabox", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "1.5"
        }, 
        {
            "build_date": "2020-12-07_17:29:28", 
            "changelog": "", 
            "description": "上海电信IPTV，4K IPTV 一键开启", 
            "home_url": "Module_shiptv.asp", 
            "md5": "88ba8f89e763cebade112f7e994fe977", 
            "name": "shiptv", 
            "tar_url": "shiptv/shiptv.tar.gz", 
            "title": "上海电信IPTV", 
            "version": "1.1"
        }, 
        {
            "build_date": "2020-12-07_17:29:28", 
            "changelog": "", 
            "description": "VPN全家桶, ver 4.29 build 9680", 
            "home_url": "Module_softether.asp", 
            "md5": "58f72b87626af884dc73681d72a86672", 
            "name": "softether", 
            "tar_url": "softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "1.9"
        }, 
        {
            "build_date": "2020-12-07_17:29:29", 
            "changelog": "", 
            "description": "让路由器运行更稳定~", 
            "home_url": "Module_swap.asp", 
            "md5": "a6cea21ed0a6a789e751a034917d43d9", 
            "name": "swap", 
            "tar_url": "swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.1"
        }, 
        {
            "build_date": "2020-12-07_17:29:29", 
            "changelog": "", 
            "description": "轻松用U盘挂载jffs", 
            "home_url": "Module_usb2jffs.asp", 
            "md5": "c4e68422c45a1768a5e2ec6ece674bb3", 
            "name": "usb2jffs", 
            "tar_url": "usb2jffs/usb2jffs.tar.gz", 
            "title": "USB2JFFS", 
            "version": "1.6"
        }, 
        {
            "build_date": "2020-12-07_17:29:28", 
            "changelog": "", 
            "description": "wifi boost: 路由器WiFi功率增强，增加信号覆盖范围。", 
            "home_url": "Module_wifiboost.asp", 
            "md5": "146d047a9a961b4d7ecea7e3e7d31f68", 
            "name": "wifiboost", 
            "port": "8083", 
            "server": "42.192.18.234", 
            "tar_url": "wifiboost/wifiboost.tar.gz", 
            "title": "wifi boost", 
            "version": "3.5"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/koolshare/koolshare.github.io/master", 
    "md5": "bd77ba4f22c0ad3f700f1a52e35d631a", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "1.6.6"
}